% Script to generate RANDLi matrices (i = 1 to 6) as per Kaczmarz paper Table 2
% Dimensions: 5000 x 500, Density: 20%, Rank: 500, Condition Number: 10^i

m = 2500;         % Number of rows
n = 2500;          % Number of columns
density = 0.20;   % 20% nonzero density

for i = 1:6
    % Condition number is 10^i
    kappa = 10^i;
    
    % sprandn uses the reciprocal of the condition number to enforce kappa
    rc = 1 / kappa; 
    
    fprintf('Generating RANDL%d with condition number 1e%d...\n', i, i);
    
    % Generate the sparse matrix
    A = sprandn(m, n, density, rc);
    
    % Define output filename
    filename = sprintf('RANDL%d.mtx', i);
    
    % =========================================================
    % Inline export to Matrix Market (.mtx) format
    % =========================================================
    
    % Find nonzero elements
    [row, col, val] = find(A);
    [m_A, n_A] = size(A);
    nz = length(val);
    
    % Open file for writing
    fid = fopen(filename, 'w');
    if fid == -1
        error('Cannot open file %s for writing.', filename);
    end
    
    % Write the Matrix Market header
    fprintf(fid, '%%%%MatrixMarket matrix coordinate real general\n');
    fprintf(fid, '%% Generated by MATLAB (RANDLi i=%d)\n', i);
    fprintf(fid, '%d %d %d\n', m_A, n_A, nz);
    
    % Write the data points (row, column, value)
    for k = 1:nz
        fprintf(fid, '%d %d %0.15g\n', row(k), col(k), val(k));
    end
    
    % Close the file
    fclose(fid);
    fprintf('Saved %s\n\n', filename);
end

fprintf('All RANDLi matrices (1 through 6) have been generated and saved successfully.\n');